spring.application.name=ecommerce-email
server.port=8081

# Token
api.security.token.secret=${JWT_SECRET}

# RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USER}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
email.queue.name=${EMAIL_QUEUE_NAME}
## Retry in case of Exception
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-retries=2
### Interval between attempts in milliseconds (5 minutes)
spring.rabbitmq.listener.simple.retry.initial-interval=300000
spring.rabbitmq.listener.simple.default-requeue-rejected=false

# MongoDB
spring.mongodb.username=${MONGO_USER}
spring.mongodb.password=${MONGO_PASSWORD}
spring.mongodb.host=${MONGO_HOST}
spring.mongodb.port=27017
spring.mongodb.database=${MONGO_DB}
spring.mongodb.authentication-database=admin

# SMTP
spring.mail.host=${SMTP_HOST}
spring.mail.port=587
spring.mail.username=${SMTP_USER}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true