spring.application.name=ecommerce
server.port=8080

# Datasource
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

# Redis
api.redis.timeout=${REDIS_TIMEOUT}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.password=${REDIS_PASSWORD}
spring.cache.type=redis

# Token
api.security.token.secret=${JWT_SECRET}
api.security.token.issuer=${TOKEN_ISSUER}
api.security.token.expiration-hours=${TOKEN_EXPIRATION_HOURS}
api.security.token.timezone=${TIMEZONE}

# Infra
infra.front.endpoints=${FRONT_ENDPOINTS}

# data.sql
spring.sql.init.data-locations=classpath:data.sql
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always